import React from 'react'
import { NavLink } from 'react-router-dom'
import {
  FiBook,
  FiLock,
  FiSettings,
  FiGitPullRequest,
  FiUserCheck,
  FiUsers,
  FiGrid,
  FiAlertOctagon,
  FiFile,
  FiThumbsUp,
  FiCreditCard,
} from 'react-icons/fi'
import { BiUserCircle } from 'react-icons/bi'
import { RiBankLine } from 'react-icons/ri'
import { FaCoins, FaRegChartBar } from 'react-icons/fa'

const _nav = [
  {
    _component: 'CNavGroup',
    as: NavLink,
    anchor: 'Administración',
    to: '/to',
    icon: <FiLock size={20} style={{ marginRight: '20px', marginLeft: '7px' }} />,
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Usuarios',
        to: '/usuarios',
        icon: <FiUsers size={16} style={{ marginRight: '4px' }} />,
        objeto: 'Modulo Usuarios',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Conectados',
        to: '/conectados',
        icon: <FiUsers size={16} style={{ marginRight: '4px' }} />,
        objeto: 'Modulo Conectados',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Perfiles',
        icon: <BiUserCircle size={18} style={{ marginRight: '4px' }} />,
        to: '/perfiles',
        objeto: 'Modulo Perfiles',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Roles',
        icon: <FiSettings size={16} style={{ marginRight: '4px' }} />,
        to: '/roles',
        objeto: 'Modulo Roles',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Permisos',
        icon: <FiUserCheck size={16} style={{ marginRight: '4px' }} />,
        to: '/permisos',
        objeto: 'Modulo Permisos',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Políticas',
        icon: <FiBook size={16} style={{ marginRight: '4px' }} />,
        to: '/politicas',
        objeto: 'Modulo Politicas',
      },
    ],
  },
  {
    _component: 'CNavGroup',
    as: NavLink,
    anchor: 'Configuración',
    to: '/to',
    icon: <FiSettings size={20} style={{ marginRight: '20px', marginLeft: '7px' }} />,
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Condiciones',
        icon: <FiAlertOctagon size={16} style={{ marginRight: '4px' }} />,
        to: '/condiciones',
        objeto: 'Modulo Condiciones',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Grupos',
        icon: <FiUsers size={16} style={{ marginRight: '4px' }} />,
        to: '/grupos',
        objeto: 'Modulo Grupos Autorizacion',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Autorizacion',
        icon: <FiThumbsUp size={16} style={{ marginRight: '4px' }} />,
        to: '/autorizacion',
        objeto: 'Modulo Autorizacion',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Estado Pago',
        icon: <FiGrid size={16} style={{ marginRight: '4px' }} />,
        to: '/estadosflujo',
        objeto: 'Modulo Estados Pago',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Tipo Flujo',
        icon: <FiGitPullRequest size={16} style={{ marginRight: '4px' }} />,
        to: '/tipoflujo',
        objeto: 'Modulo Tipos Flujo',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Archivos Pagos',
        icon: <FiFile size={16} style={{ marginRight: '4px' }} />,
        to: '/archivoflujo',
        objeto: 'Modulo Archivos Pago',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Bancos',
        icon: <RiBankLine size={18} style={{ marginRight: '4px' }} />,
        to: '/bancos',
        objeto: 'Modulo Bancos',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Monedas',
        icon: <FaCoins size={16} style={{ marginRight: '4px' }} />,
        to: '/monedas',
        objeto: 'Modulo Monedas',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cuentas',
        icon: <FiCreditCard size={16} style={{ marginRight: '4px' }} />,
        to: '/cuentas',
        objeto: 'Modulo Cuentas',
      },
    ],
  },
  {
    _component: 'CNavGroup',
    as: NavLink,
    anchor: 'Pagos',
    to: '/to',
    icon: <FiCreditCard size={20} style={{ marginRight: '20px', marginLeft: '7px' }} />,
    items: [
      {
        _component: 'CNavGroup',
        anchor: 'Autorizar Pagos',
        icon: <FiCreditCard size={16} style={{ marginRight: '4px' }} />,
        as: NavLink,
        items: [
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Bancaria',
            to: '/pagos/bancario',
          },
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Transferencia',
            to: '/pagos/transferencia',
          },
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Interna',
            to: '/pagos/interna',
          },
        ],
      },
      {
        _component: 'CNavGroup',
        anchor: 'Compensar Pagos',
        icon: <FiCreditCard size={17} />,
        as: NavLink,
        objeto: 'Modulo Compensacion Pagos',
        items: [
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Bancaria',
            to: '/compensacion/bancario',
          },
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Transferencia',
            to: '/compensacion/transferencia',
          },
          {
            _component: 'CNavItem',
            as: NavLink,
            anchor: 'Interna',
            to: '/compensacion/interna',
          },
        ],
      },
    ],
  },
  {
    _component: 'CNavGroup',
    as: NavLink,
    anchor: 'Reportes',
    to: '/to',
    icon: <FaRegChartBar size={20} style={{ marginRight: '20px', marginLeft: '7px' }} />,
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Pagos Pendientes',
        to: '/to',
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Días Conectados',
        to: '/to',
      },
    ],
  },
]

export default _nav
